/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMeusLeadsRouteImport } from './routes/_authenticated/meus-leads'
import { Route as AuthenticatedLeadsEmMassaRouteImport } from './routes/_authenticated/leads-em-massa'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedKanbanMassaRouteImport } from './routes/_authenticated/kanban-massa'
import { Route as AuthenticatedKanbanCaptacaoMassaRouteImport } from './routes/_authenticated/kanban-captacao-massa'
import { Route as AuthenticatedKanbanCaptacaoRouteImport } from './routes/_authenticated/kanban-captacao'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedDistribuicaoRouteImport } from './routes/_authenticated/distribuicao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorretoresRouteImport } from './routes/_authenticated/corretores'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'
import { Route as AuthenticatedLeadsEmMassaBatchIdRouteImport } from './routes/_authenticated/leads-em-massa.$batchId'
import { Route as AuthenticatedConfiguracoesKanbanRouteImport } from './routes/_authenticated/configuracoes.kanban'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeusLeadsRoute = AuthenticatedMeusLeadsRouteImport.update({
  id: '/meus-leads',
  path: '/meus-leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsEmMassaRoute =
  AuthenticatedLeadsEmMassaRouteImport.update({
    id: '/leads-em-massa',
    path: '/leads-em-massa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKanbanMassaRoute =
  AuthenticatedKanbanMassaRouteImport.update({
    id: '/kanban-massa',
    path: '/kanban-massa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKanbanCaptacaoMassaRoute =
  AuthenticatedKanbanCaptacaoMassaRouteImport.update({
    id: '/kanban-captacao-massa',
    path: '/kanban-captacao-massa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKanbanCaptacaoRoute =
  AuthenticatedKanbanCaptacaoRouteImport.update({
    id: '/kanban-captacao',
    path: '/kanban-captacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDistribuicaoRoute =
  AuthenticatedDistribuicaoRouteImport.update({
    id: '/distribuicao',
    path: '/distribuicao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCorretoresRoute = AuthenticatedCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)
const AuthenticatedLeadsEmMassaBatchIdRoute =
  AuthenticatedLeadsEmMassaBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => AuthenticatedLeadsEmMassaRoute,
  } as any)
const AuthenticatedConfiguracoesKanbanRoute =
  AuthenticatedConfiguracoesKanbanRouteImport.update({
    id: '/configuracoes/kanban',
    path: '/configuracoes/kanban',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribuicao': typeof AuthenticatedDistribuicaoRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/kanban-captacao': typeof AuthenticatedKanbanCaptacaoRoute
  '/kanban-captacao-massa': typeof AuthenticatedKanbanCaptacaoMassaRoute
  '/kanban-massa': typeof AuthenticatedKanbanMassaRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/leads-em-massa': typeof AuthenticatedLeadsEmMassaRouteWithChildren
  '/meus-leads': typeof AuthenticatedMeusLeadsRoute
  '/configuracoes/kanban': typeof AuthenticatedConfiguracoesKanbanRoute
  '/leads-em-massa/$batchId': typeof AuthenticatedLeadsEmMassaBatchIdRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribuicao': typeof AuthenticatedDistribuicaoRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/kanban-captacao': typeof AuthenticatedKanbanCaptacaoRoute
  '/kanban-captacao-massa': typeof AuthenticatedKanbanCaptacaoMassaRoute
  '/kanban-massa': typeof AuthenticatedKanbanMassaRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/leads-em-massa': typeof AuthenticatedLeadsEmMassaRouteWithChildren
  '/meus-leads': typeof AuthenticatedMeusLeadsRoute
  '/configuracoes/kanban': typeof AuthenticatedConfiguracoesKanbanRoute
  '/leads-em-massa/$batchId': typeof AuthenticatedLeadsEmMassaBatchIdRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/corretores': typeof AuthenticatedCorretoresRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/distribuicao': typeof AuthenticatedDistribuicaoRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/kanban-captacao': typeof AuthenticatedKanbanCaptacaoRoute
  '/_authenticated/kanban-captacao-massa': typeof AuthenticatedKanbanCaptacaoMassaRoute
  '/_authenticated/kanban-massa': typeof AuthenticatedKanbanMassaRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/leads-em-massa': typeof AuthenticatedLeadsEmMassaRouteWithChildren
  '/_authenticated/meus-leads': typeof AuthenticatedMeusLeadsRoute
  '/_authenticated/configuracoes/kanban': typeof AuthenticatedConfiguracoesKanbanRoute
  '/_authenticated/leads-em-massa/$batchId': typeof AuthenticatedLeadsEmMassaBatchIdRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/corretores'
    | '/dashboard'
    | '/distribuicao'
    | '/kanban'
    | '/kanban-captacao'
    | '/kanban-captacao-massa'
    | '/kanban-massa'
    | '/leads'
    | '/leads-em-massa'
    | '/meus-leads'
    | '/configuracoes/kanban'
    | '/leads-em-massa/$batchId'
    | '/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/corretores'
    | '/dashboard'
    | '/distribuicao'
    | '/kanban'
    | '/kanban-captacao'
    | '/kanban-captacao-massa'
    | '/kanban-massa'
    | '/leads'
    | '/leads-em-massa'
    | '/meus-leads'
    | '/configuracoes/kanban'
    | '/leads-em-massa/$batchId'
    | '/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/corretores'
    | '/_authenticated/dashboard'
    | '/_authenticated/distribuicao'
    | '/_authenticated/kanban'
    | '/_authenticated/kanban-captacao'
    | '/_authenticated/kanban-captacao-massa'
    | '/_authenticated/kanban-massa'
    | '/_authenticated/leads'
    | '/_authenticated/leads-em-massa'
    | '/_authenticated/meus-leads'
    | '/_authenticated/configuracoes/kanban'
    | '/_authenticated/leads-em-massa/$batchId'
    | '/_authenticated/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meus-leads': {
      id: '/_authenticated/meus-leads'
      path: '/meus-leads'
      fullPath: '/meus-leads'
      preLoaderRoute: typeof AuthenticatedMeusLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads-em-massa': {
      id: '/_authenticated/leads-em-massa'
      path: '/leads-em-massa'
      fullPath: '/leads-em-massa'
      preLoaderRoute: typeof AuthenticatedLeadsEmMassaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kanban-massa': {
      id: '/_authenticated/kanban-massa'
      path: '/kanban-massa'
      fullPath: '/kanban-massa'
      preLoaderRoute: typeof AuthenticatedKanbanMassaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kanban-captacao-massa': {
      id: '/_authenticated/kanban-captacao-massa'
      path: '/kanban-captacao-massa'
      fullPath: '/kanban-captacao-massa'
      preLoaderRoute: typeof AuthenticatedKanbanCaptacaoMassaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kanban-captacao': {
      id: '/_authenticated/kanban-captacao'
      path: '/kanban-captacao'
      fullPath: '/kanban-captacao'
      preLoaderRoute: typeof AuthenticatedKanbanCaptacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/distribuicao': {
      id: '/_authenticated/distribuicao'
      path: '/distribuicao'
      fullPath: '/distribuicao'
      preLoaderRoute: typeof AuthenticatedDistribuicaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corretores': {
      id: '/_authenticated/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AuthenticatedCorretoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/leads-em-massa/$batchId': {
      id: '/_authenticated/leads-em-massa/$batchId'
      path: '/$batchId'
      fullPath: '/leads-em-massa/$batchId'
      preLoaderRoute: typeof AuthenticatedLeadsEmMassaBatchIdRouteImport
      parentRoute: typeof AuthenticatedLeadsEmMassaRoute
    }
    '/_authenticated/configuracoes/kanban': {
      id: '/_authenticated/configuracoes/kanban'
      path: '/configuracoes/kanban'
      fullPath: '/configuracoes/kanban'
      preLoaderRoute: typeof AuthenticatedConfiguracoesKanbanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

interface AuthenticatedLeadsEmMassaRouteChildren {
  AuthenticatedLeadsEmMassaBatchIdRoute: typeof AuthenticatedLeadsEmMassaBatchIdRoute
}

const AuthenticatedLeadsEmMassaRouteChildren: AuthenticatedLeadsEmMassaRouteChildren =
  {
    AuthenticatedLeadsEmMassaBatchIdRoute:
      AuthenticatedLeadsEmMassaBatchIdRoute,
  }

const AuthenticatedLeadsEmMassaRouteWithChildren =
  AuthenticatedLeadsEmMassaRoute._addFileChildren(
    AuthenticatedLeadsEmMassaRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCorretoresRoute: typeof AuthenticatedCorretoresRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistribuicaoRoute: typeof AuthenticatedDistribuicaoRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedKanbanCaptacaoRoute: typeof AuthenticatedKanbanCaptacaoRoute
  AuthenticatedKanbanCaptacaoMassaRoute: typeof AuthenticatedKanbanCaptacaoMassaRoute
  AuthenticatedKanbanMassaRoute: typeof AuthenticatedKanbanMassaRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
  AuthenticatedLeadsEmMassaRoute: typeof AuthenticatedLeadsEmMassaRouteWithChildren
  AuthenticatedMeusLeadsRoute: typeof AuthenticatedMeusLeadsRoute
  AuthenticatedConfiguracoesKanbanRoute: typeof AuthenticatedConfiguracoesKanbanRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCorretoresRoute: AuthenticatedCorretoresRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistribuicaoRoute: AuthenticatedDistribuicaoRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedKanbanCaptacaoRoute: AuthenticatedKanbanCaptacaoRoute,
  AuthenticatedKanbanCaptacaoMassaRoute: AuthenticatedKanbanCaptacaoMassaRoute,
  AuthenticatedKanbanMassaRoute: AuthenticatedKanbanMassaRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedLeadsEmMassaRoute: AuthenticatedLeadsEmMassaRouteWithChildren,
  AuthenticatedMeusLeadsRoute: AuthenticatedMeusLeadsRoute,
  AuthenticatedConfiguracoesKanbanRoute: AuthenticatedConfiguracoesKanbanRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
